// Generated by CoffeeScript 1.6.2
(function() {
  var create, encode, handleDemoFormSubmit, prettify, setupCode, setupLinks, setupNav, slugify, successElem;

  setupCode = function() {
    var insertCode;

    insertCode = function(container, pre) {
      var content, i, indentation, l, line, lines, m;

      if (container.length === 0 || pre.length === 0) {
        return;
      }
      content = container.html();
      lines = content.split("\n");
      indentation = void 0;
      content = "";
      i = 0;
      l = lines.length;
      while (i < l) {
        line = lines[i];
        if (i > 0 && i < l - 1) {
          if (indentation === undefined) {
            m = line.match(/^(\ *)/);
            if (m) {
              indentation = m[1];
            }
          }
          line = line.replace(new RegExp("^" + indentation), "");
          content += line + "\n";
        }
        ++i;
      }
      return pre.append(prettify(content));
    };
    $(".demo").each(function() {
      var demo, htmlDemo, htmlPre, scriptDemo, scriptPre;

      demo = $(this);
      htmlDemo = demo.find("div[data-html]");
      htmlPre = demo.find("pre[data-html]");
      scriptDemo = demo.find("script[data-script]");
      scriptPre = demo.find("pre[data-script]");
      insertCode(htmlDemo, htmlPre);
      return insertCode(scriptDemo, scriptPre);
    });
    return $(".highlight-col3-table tbody tr").each(function() {
      var codeCol;

      codeCol = $(this).children().eq(2);
      return codeCol.html(prettify(codeCol.html()));
    });
  };

  encode = function(value) {
    return $("<div/>").text(value).html();
  };

  prettify = function(str) {
    return prettyPrintOne(encode(str));
  };

  create = function(type) {
    return $(document.createElement(type));
  };

  slugify = function(title) {
    return title.replace(/\s/g, "-").toLowerCase();
  };

  setupLinks = function() {
    var handleHashClick;

    handleHashClick = function(e) {
      var elem, id;

      e.preventDefault();
      id = $(this).attr("href");
      elem = $(id).scrollView(function() {
        return window.location.hash = id;
      });
      if (elem.length === 0) {
        alert("Sorry those docs are still in progress !");
      }
      return false;
    };
    $(document).on("click", "a[href^=#]", handleHashClick);
    return $("a[data-link]").each(function() {
      var sel;

      sel = "#" + slugify($(this).html());
      $(this).attr("href", sel);
      if ($(sel).length === 0) {
        return console.log("missing: ", sel);
      }
    });
  };

  setupNav = function() {
    var anchorTemplate, checkViewport, headerTemplate, navList, sections, setupNavAnchor, setupNavHeading;

    sections = [];
    setupNavHeading = function() {
      var container, first, heading, li, section, slug;

      section = $(this);
      heading = section.data("nav-heading");
      slug = slugify(heading);
      first = section.children(":first");
      if (!first.is("h3")) {
        section.prepend(create("h3").html(heading));
      }
      section.attr("id", slug);
      li = headerTemplate({
        heading: heading
      });
      navList.append(li);
      container = create("div").addClass("nav-anchors");
      $(this).find("[data-nav-anchor]").each(function() {
        return setupNavAnchor(container, $(this));
      });
      navList.append(container);
      return sections.push({
        elem: section,
        container: container,
        shown: false
      });
    };
    setupNavAnchor = function(container, anchor) {
      var first, li, slug, title;

      title = anchor.data("nav-anchor");
      slug = slugify(title);
      first = anchor.children(":first");
      if (!first.is("h4")) {
        anchor.prepend(create("h4").html(title));
      }
      anchor.attr("id", slug);
      li = $(anchorTemplate({
        title: title,
        slug: slug
      }));
      return container.append(li);
    };
    headerTemplate = _.template("<li class=\"nav-header\"><%= heading %></li>");
    anchorTemplate = _.template("<li><a href=\"#<%= slug %>\"><%= title %></a></li>");
    navList = $("#nav-list");
    $("[data-nav-heading]").each(setupNavHeading);
    checkViewport = function() {
      return _.each(sections, function(section) {
        var onScreen;

        onScreen = section.elem.is(":in-viewport");
        if (onScreen && !section.shown) {
          section.container.slideDown();
          section.shown = true;
          return console.log("show", section.elem);
        } else if (!onScreen && section.shown) {
          section.container.slideUp();
          section.shown = false;
          return console.log("false", section.elem);
        }
      });
    };
    return $(document).scroll(_.throttle(checkViewport));
  };

  encode = function(value) {
    return $("<div/>").text(value).html();
  };

  prettify = function(str) {
    return prettyPrintOne(encode(str));
  };

  create = function(type) {
    return $(document.createElement(type));
  };

  slugify = function(title) {
    return title.replace(/\s/g, "-").toLowerCase();
  };

  $.fn.togglers = function() {
    var container, togglers;

    container = $(this);
    togglers = container.find("[data-toggle]");
    return togglers.each(function() {
      var btn, elem, selector;

      btn = $(this);
      selector = btn.attr("data-toggle");
      elem = container.find(selector);
      if (elem.length === 0) {
        return;
      }
      return btn.click(function() {
        var text, visible;

        visible = elem.is(":visible");
        text = btn.html();
        btn.html(text.replace(/hide|show/i, (visible ? "Show" : "Hide")));
        if (visible) {
          return elem.slideUp();
        } else {
          return elem.slideDown();
        }
      });
    });
  };

  handleDemoFormSubmit = function() {
    $(this).append(successElem.show().stop().delay(2000).fadeOut());
    return false;
  };

  successElem = $("<div class=\"alert alert-success\"><strong>" + "Validation successful ! </strong> If this was a real form, it would be submitting right now..." + "</div>");

  $(document).ready(function() {
    setupCode();
    setupNav();
    setupLinks();
    $(".loading-cover").fadeOut("fast");
    window.prettyPrint();
    return $(document).on("submit", "form", handleDemoFormSubmit);
  });

}).call(this);
