// Generated by CoffeeScript 1.6.2
(function() {
  var $document, $window, create, encode, handleDemoFormSubmit, prettify, setupCode, setupLinks, setupNav, setupWindow, slugify, successElem;

  setupCode = function() {
    var insertCode;

    insertCode = function(container, pre) {
      var content, i, indentation, l, line, lines, m;

      if (container.length === 0 || pre.length === 0) {
        return;
      }
      content = container.html();
      lines = content.split("\n");
      indentation = void 0;
      content = "";
      i = 0;
      l = lines.length;
      while (i < l) {
        line = lines[i];
        if (i > 0 && i < l - 1) {
          if (indentation === undefined) {
            m = line.match(/^(\ *)/);
            if (m) {
              indentation = m[1];
            }
          }
          line = line.replace(new RegExp("^" + indentation), "");
          content += line + "\n";
        }
        ++i;
      }
      return pre.append(prettify(content));
    };
    $(".demo").each(function() {
      var demo, htmlDemo, htmlPre, scriptDemo, scriptPre;

      demo = $(this);
      htmlDemo = demo.find("div[data-html]");
      htmlPre = demo.find("pre[data-html]");
      scriptDemo = demo.find("script[data-script]");
      scriptPre = demo.find("pre[data-script]");
      insertCode(htmlDemo, htmlPre);
      return insertCode(scriptDemo, scriptPre);
    });
    return $(".highlight-col3-table tbody tr").each(function() {
      var codeCol;

      codeCol = $(this).children().eq(2);
      return codeCol.html(prettify(codeCol.html()));
    });
  };

  encode = function(value) {
    return $("<div/>").text(value).html();
  };

  prettify = function(str) {
    return prettyPrintOne(encode(str));
  };

  create = function(type) {
    return $(document.createElement(type));
  };

  slugify = function(title) {
    return title.replace(/\s/g, "-").toLowerCase();
  };

  setupLinks = function() {
    var get;

    get = function(id) {
      return $("[nav-id=" + id + "]");
    };
    $window.on('hashchange', function() {
      var elem;

      console.log("hash change");
      elem = get(location.hash.substr(1));
      if (elem.length === 0) {
        return alert("Sorry those docs are still in progress !");
      } else {
        return $('html,body').animate({
          scrollTop: elem.offset().top
        }, {
          duration: 1000,
          easing: 'easeInOutExpo'
        });
      }
    });
    $window.trigger('hashchange');
    return $("a[data-link]").each(function() {
      var id;

      id = slugify($(this).text());
      $(this).attr('href', '#' + id);
      if (get(id).length === 0) {
        return console.log("missing: ", id);
      }
    });
  };

  setupNav = function() {
    var anchorTemplate, checkViewport, headerTemplate, navList, sections, setupNavAnchor, setupNavHeading;

    sections = [];
    setupNavHeading = function() {
      var container, first, heading, li, section, slug;

      section = $(this);
      heading = section.data("nav-heading");
      slug = slugify(heading);
      first = section.children(":first");
      if (!first.is("h3")) {
        section.prepend(create("h3").html(heading));
      }
      section.attr("nav-id", slug);
      li = headerTemplate({
        heading: heading
      });
      navList.append(li);
      container = create("div").addClass("nav-anchors");
      $(this).find("[data-nav-anchor]").each(function() {
        return setupNavAnchor(container, $(this));
      });
      navList.append(container);
      return sections.push({
        elem: section,
        container: container,
        shown: false
      });
    };
    setupNavAnchor = function(container, anchor) {
      var first, li, slug, title;

      title = anchor.data("nav-anchor");
      slug = slugify(title);
      first = anchor.children(":first");
      if (!first.is("h4")) {
        anchor.prepend(create("h4").html(title));
      }
      anchor.attr("nav-id", slug);
      li = $(anchorTemplate({
        title: title,
        slug: slug
      }));
      return container.append(li);
    };
    headerTemplate = _.template("<li class=\"nav-header\"><%= heading %></li>");
    anchorTemplate = _.template("<li><a href=\"#<%= slug %>\"><%= title %></a></li>");
    navList = $("#nav-list");
    $("[data-nav-heading]").each(setupNavHeading);
    checkViewport = function() {
      return;
      return _.each(sections, function(section) {
        var onScreen;

        onScreen = section.elem.is(":in-viewport");
        if (onScreen && !section.shown) {
          section.shown = true;
          return console.log("show", section.elem);
        } else if (!onScreen && section.shown) {
          section.shown = false;
          return console.log("false", section.elem);
        }
      });
    };
    return $document.scroll(_.throttle(checkViewport));
  };

  encode = function(value) {
    return $("<div/>").text(value).html();
  };

  prettify = function(str) {
    return prettyPrintOne(encode(str));
  };

  create = function(type) {
    return $(document.createElement(type));
  };

  slugify = function(title) {
    return title.replace(/\s/g, "-").toLowerCase();
  };

  $.fn.togglers = function() {
    var container, togglers;

    container = $(this);
    togglers = container.find("[data-toggle]");
    return togglers.each(function() {
      var btn, elem, selector;

      btn = $(this);
      selector = btn.attr("data-toggle");
      elem = container.find(selector);
      if (elem.length === 0) {
        return;
      }
      return btn.click(function() {
        var text, visible;

        visible = elem.is(":visible");
        text = btn.html();
        btn.html(text.replace(/hide|show/i, (visible ? "Show" : "Hide")));
        if (visible) {
          return elem.slideUp();
        } else {
          return elem.slideDown();
        }
      });
    });
  };

  handleDemoFormSubmit = function() {
    $(this).append(successElem.show().stop().delay(2000).fadeOut());
    return false;
  };

  successElem = $("<div class=\"alert alert-success\"><strong>" + "Validation successful ! </strong> If this was a real form, it would be submitting right now..." + "</div>");

  $window = $(window);

  $document = $(document);

  $document.ready(function() {
    setupCode();
    setupNav();
    setupLinks();
    setupWindow();
    $(".loading-cover").fadeOut("fast");
    window.prettyPrint();
    return $document.on("submit", "form", handleDemoFormSubmit);
  });

  setupWindow = function() {
    var resizeViewport, sidebar;

    sidebar = $('.sidebar-nav');
    resizeViewport = function() {
      console.log("resize");
      return sidebar.height($window.height());
    };
    $window.resize(_.debounce(resizeViewport));
    return resizeViewport();
  };

}).call(this);
