// Generated by CoffeeScript 1.6.2
CronEngine.directive("arrayInput", function(templates) {
  return {
    restrict: 'EAC',
    replace: true,
    scope: {
      label: "@label",
      placeholder: "@placeholder",
      modelName: "@modelName",
      validate: "@validate"
    },
    template: templates("array-input"),
    controller: function($scope, $element, $timeout) {
      var arr, getList;

      arr = function() {
        var a, name;

        name = $scope.modelName;
        if (!name) {
          throw "array input: 'modalName' missing";
        }
        a = $scope.$parent[name];
        if (!a) {
          return [];
        }
        return a;
      };
      $timeout(function() {
        return $scope.$parent.$watch($scope.modelName, getList);
      });
      getList = function() {
        return $scope.list = _.map(arr(), function(val, index) {
          return {
            val: val,
            index: index
          };
        });
      };
      $element.on('keyup', '.existing-item', function() {
        var index;

        index = $(this).data('index');
        return arr()[index] = $(this).val();
      });
      $scope.addItem = function() {
        arr().push('');
        return getList();
      };
      $scope.removeItem = function(item) {
        arr().remove(item.index);
        return getList();
      };
      return null;
    }
  };
});
