// Generated by CoffeeScript 1.6.2
CronEngine.filter('date', function() {
  return function(input) {
    var ms;

    ms = parseInt(input, 10);
    if (isNaN(ms)) {
      return '';
    }
    return moment(ms).format("YYYY-MM-DD HH:mm:ss");
  };
});
