// Generated by CoffeeScript 1.6.2
CronEngine.filter('duration', function() {
  return function(input) {
    var ms, result;

    ms = parseInt(input, 10);
    if (isNaN(ms)) {
      return '';
    }
    result = '';
    if (ms < 1000) {
      result = ms + " ms";
    } else {
      result = moment.duration(ms, "ms").humanize();
    }
    return result;
  };
});
