// Generated by CoffeeScript 1.6.2
CronEngine.filter('headerify', function(templates) {
  var label;

  label = templates('label');
  return function(input, includeValue) {
    var arr;

    if (includeValue == null) {
      includeValue = false;
    }
    arr = input;
    if (!($.isArray(arr) && arr.length > 0)) {
      return label({
        type: 'default',
        content: 'None'
      });
    }
    arr = _.map(arr, function(str) {
      var content, key, parts, val;

      parts = str.split(/\s*:\s*/);
      key = parts[0];
      val = parts[1];
      content = key;
      if (includeValue) {
        content += ': ' + val;
      }
      return label({
        type: 'warning',
        content: content
      });
    });
    return arr.join(' ');
  };
});
