// Generated by CoffeeScript 1.6.2
CronEngine.filter('tagify', function(templates) {
  var label;

  label = templates('label');
  return function(input) {
    var arr;

    arr = input;
    if (!($.isArray(arr) && arr.length > 0)) {
      return label({
        type: 'default',
        content: 'None'
      });
    }
    arr = _.map(arr, function(str) {
      return label({
        type: 'info',
        content: str
      });
    });
    return arr.join(' ');
  };
});
