// Generated by CoffeeScript 1.6.2
CronEngine.controller("CronModalController", function($scope, $route, api, $element) {
  var editModal, newJob, updateJob;

  console.log("init modal controller");
  editModal = $("#cronModal");
  editModal.on("hidden", function() {
    return $scope.back();
  });
  newJob = {
    cronJobId: null,
    url: "http://www.google.com",
    timeout: 60,
    frequency: "every 5 hours",
    tagList: ["my-tag"],
    headerList: []
  };
  updateJob = function(data) {
    _.extend($scope, data);
    return $scope.$apply();
  };
  $scope.isNew = function() {
    return !$scope.cronJobId;
  };
  $scope.type = function() {
    if ($scope.isNew()) {
      return "New";
    } else {
      return "Edit";
    }
  };
  $scope.$on('cron.add', function() {
    console.log('add');
    updateJob(newJob);
    return editModal.modal("show");
  });
  $scope.$on('cron.edit', function(event, params) {
    console.log('edit');
    return api.cronjobs.read(params.id).done(function(job) {
      updateJob(job);
      return editModal.modal("show");
    });
  });
  return $scope.commitJob = function() {
    var data;

    console.log('commit!');
    data = _.pick($scope, 'url', 'frequency', 'tagList', 'headerList', 'timeout');
    console.log(data);
    return $element.find('form').validate(function(r) {
      var req;

      if (!r) {
        return;
      }
      req = $scope.isNew() ? api.cronjobs.create(data) : api.cronjobs.update($scope.cronJobId, data);
      return req.done(function() {
        editModal.modal('hide');
        return $scope.$root.$broadcast('cron.jobs.change');
      });
    });
  };
});
