// Generated by CoffeeScript 1.6.2
CronEngine.controller("CronJobsController", function($scope, $route, api, $location, cronCarousel) {
  console.log("init cronjobs");
  $scope.$on("auth.login", function() {
    return $scope.refresh();
  });
  $scope.$on("cron.jobs", function() {
    cronCarousel(0);
    return $scope.refresh();
  });
  $scope.jobs = [];
  $scope.refresh = function() {
    console.log("jobs refresh");
    return api.cronjobs.read().always(function(jobs, result, ajax) {
      if (result === 'success') {
        $scope.jobs = jobs;
      }
      return $scope.$apply();
    });
  };
  $scope.select = function(job) {
    return window.location.hash = "/cron-jobs/" + job.cronJobId;
  };
  $scope.edit = function(job, $event) {
    $event.stopPropagation();
    return window.location.hash = "/cron-jobs/edit/" + job.cronJobId;
  };
  return $scope.remove = function(job, $event) {
    var index;

    $event.stopPropagation();
    index = $scope.jobs.indexOf(job);
    if (index === -1) {
      return console.error("missing job");
    }
    if (!confirm("Are you sure you want to delete this job ?")) {
      return;
    }
    return api.cronjobs.del(job.cronJobId).always(function(data, result) {
      api.cache.clear();
      return $scope.$root.$broadcast('cron.jobs');
    });
  };
});
