// Generated by CoffeeScript 1.6.2
CronEngine.controller("EngineController", function($scope, slugify, $timeout) {
  console.log("init engine");
  $scope.back = function() {
    if (history) {
      return history.back();
    }
  };
  $(function() {
    return $scope.$broadcast('app.ready');
  });
  $scope.$on('section', function(event, section) {
    return $scope.changeSection(section);
  });
  $scope.sections = {
    cron: "Cron Jobs",
    subs: "Subscribers"
  };
  $scope.activeSection = function(section) {
    if (slugify(section) === $scope.currentSection) {
      return "active";
    } else {
      return "";
    }
  };
  $scope.changeSection = function(section) {
    var className, currSection, otherSections;

    if (section === $scope.currentSection) {
      return;
    }
    console.log("change section: " + section);
    $scope.currentSection = section;
    className = slugify(section);
    currSection = $("." + className);
    otherSections = $("section:not(." + className + ")");
    if (!currSection.length) {
      console.warn("Missing section: ", section);
      currSection = $("section:first");
    }
    return otherSections.fadeOut(function() {
      return currSection.fadeIn();
    });
  };
  return $scope.changeSection($scope.sections.cron);
});
