// Generated by CoffeeScript 1.6.2
CronEngine.controller("SubscribersController", function($scope, $route, api, $location) {
  console.log("init subs");
  $scope.$on("subs", function() {
    return $scope.refresh();
  });
  $scope.$parent.subs = [];
  $scope.refresh = function() {
    console.log("subs refresh");
    return api.observers.read().always(function(subscribers, result, ajax) {
      if (result === 'success') {
        $scope.$parent.subs = subscribers;
      }
      return $scope.$apply();
    });
  };
  $scope.add = function() {
    console.log("add!");
    return window.location.hash = "/subscribers/add";
  };
  $scope.edit = function(sub) {
    console.log("edit!");
    return window.location.hash = "/subscribers/edit/" + sub.email;
  };
  return $scope.remove = function(sub) {
    console.log("remove!");
    if (!confirm("Are you sure you want to delete this subscriber ?")) {
      return;
    }
    return api.observers.del(sub.email).always(function(data, result) {
      api.cache.clear();
      return $scope.$root.$broadcast('subs');
    });
  };
});
