// Generated by CoffeeScript 1.6.2
"use strict";Array.prototype.remove = function(from, to) {
  var rest;

  rest = this.slice((to || from) + 1 || this.length);
  this.length = (from < 0 ? this.length + from : from);
  return this.push.apply(this, rest);
};

window.CronEngine = angular.module('cron-engine', []);
