// Generated by CoffeeScript 1.6.2
CronEngine.directive("hasClass", function() {
  return function(scope, element, attrs) {
    console.log("compile 'hasClass'");
    return scope.$watch(attrs.hasClass);
  };
});
