// Generated by CoffeeScript 1.6.2
CronEngine.factory("api", function() {
  var api;

  console.log("init api");
  api = new $.RestClient("http://cron.think.edu.au:8080/api/", {
    stringifyData: true,
    verbs: {
      update: "POST"
    }
  });
  api.add("cronjobs");
  api.cronjobs.addVerb("trigger", "POST");
  api.cronjobs.add("execs");
  api.add("observers");
  return api;
});
