// Generated by CoffeeScript 1.6.2
CronEngine.factory("cronCarousel", function() {
  var cronCarousel;

  console.log("init carousel");
  cronCarousel = $("#cronCarousel");
  cronCarousel.carousel({
    interval: false
  });
  return function(n) {
    return cronCarousel.carousel(n);
  };
});
