// Generated by CoffeeScript 1.6.2
CronEngine.factory("templates", function() {
  var cache;

  console.log("init templates");
  cache = {};
  return function(name) {
    var compiled, e, str, template;

    if (cache[name]) {
      return cache[name];
    }
    template = $("#" + name + "-template");
    if (template.length === 0) {
      throw "cant find template: " + name;
    }
    str = template.html();
    if (str.match(/<%=?\s*\w+\s*%>/)) {
      try {
        compiled = _.template(str);
      } catch (_error) {
        e = _error;
        throw "Underscore.js Error: " + e;
      }
      cache[name] = compiled;
    } else {
      cache[name] = str;
    }
    return cache[name];
  };
});
