// Generated by CoffeeScript 1.6.2
CronEngine.controller("AuthController", function($scope, api, $timeout) {
  var $root;

  console.log("init auth");
  $root = $scope.$root;
  $scope.username = "";
  $scope.password = "";
  if (window.localStorage) {
    $scope.username = window.localStorage.username;
    $scope.password = window.localStorage.password;
  }
  $root.hasUser = false;
  $scope.toggleAuth = function() {
    console.log("toggle");
    if ($scope.hasUser) {
      return $scope.logout();
    } else {
      return $scope.login();
    }
  };
  $scope.login = function() {
    var p, u;

    console.log("login");
    u = $scope.username;
    p = $scope.password;
    if (!u || !p) {
      return;
    }
    api.opts.username = u;
    api.opts.password = p;
    if (window.localStorage) {
      window.localStorage.username = u;
      window.localStorage.password = p;
    }
    $root.hasUser = true;
    return $root.$broadcast('auth.login');
  };
  $scope.logout = function() {
    console.log("logout");
    $scope.username = "";
    $scope.password = "";
    $root.hasUser = false;
    return $root.$broadcast('auth.logout');
  };
  return $scope.$on('app.ready', function() {
    return $scope.login();
  });
});
