// Generated by CoffeeScript 1.6.2
CronEngine.controller("CronJobController", function($scope, api, cronCarousel) {
  console.log("init cronjob");
  $scope.$on("cron.job", function(event, params) {
    cronCarousel(1);
    return $scope.refresh(params.id);
  });
  $scope.job = {};
  $scope.executions = [];
  $scope.trigger = function() {
    var id;

    id = $scope.job.cronJobId;
    if (!id) {
      return;
    }
    return api.cronjobs.trigger(id).done(function() {
      $(".trigger").html("Running...");
      return setTimeout(function() {
        return $(".trigger").html("Trigger");
      }, 2000);
    });
  };
  $scope.select = function(exec) {
    return window.location.hash = "/cron-jobs/" + $scope.job.cronJobId + "/" + exec.cronExecutionId;
  };
  return $scope.refresh = function(id) {
    console.log("job refresh", id);
    $scope.job = {};
    api.cronjobs.read(id).done(function(job) {
      $scope.job = job;
      return $scope.$apply();
    });
    $scope.executions = [];
    return api.cronjobs.execs.read(id).done(function(executions) {
      $scope.executions = executions;
      return $scope.$apply();
    });
  };
});
