// Generated by CoffeeScript 1.6.2
CronEngine.controller("SubcriberModalController", function($scope, $route, api, $element) {
  var editModal, pickData, updateSub;

  console.log("init subs modal controller");
  editModal = $("#subsModal");
  editModal.on("hidden", function() {
    return $scope.back();
  });
  $scope.$on('subs.add', function() {
    console.log('add');
    updateSub({
      email: '',
      tagList: []
    });
    return editModal.modal("show");
  });
  $scope.$on('subs.edit', function(event, params) {
    console.log('edit');
    return api.observers.read(params.email).done(function(sub) {
      updateSub(sub);
      return editModal.modal("show");
    });
  });
  pickData = function(data) {
    return _.pick(data, 'email', 'tagList');
  };
  updateSub = function(data) {
    data = pickData(data);
    console.log("update", data);
    _.extend($scope, {}, data);
    return $scope.$digest();
  };
  $scope.isNew = function() {
    return !_.find($scope.subs, function(s) {
      return s.email === $scope.email;
    });
  };
  return $scope.commitSub = function() {
    console.log('commit!');
    return $element.find('form').validate(function(r) {
      var data, req;

      if (!r) {
        return;
      }
      data = pickData($scope);
      req = $scope.isNew() ? api.observers.create(data) : api.observers.update(data.email, data);
      return req.done(function() {
        editModal.modal('hide');
        return $scope.$root.$broadcast('subs');
      });
    });
  };
});
